---
- name: without roles and a regular playbook
  hosts: localhost
  become: true
  tasks:
   - name: installed httpd
     yum:
      name: httpd
      state: installed
   - name: installed git
     yum:
      name: git
      state: installed
   - name: installed docker
     yum:
      name: docker
      state: installed
